module.exports = [
  {
    slug: "men",
    section: "fragrances",
    permalink: "fragrances/men.html",
    filter_type: "gender",
    filter_value: "Men",
    title_en: "Mens Fragrances",
    title_pt: "Perfumes Masculinos",
    title_es: "Fragancias para Hombre",
    description_en: "Bold, refined and built to last. Our curated selection of men's fragrances from the finest Arabian and European houses.",
    description_pt: "Ousados, refinados e duradouros. A nossa seleção de perfumes masculinos das melhores casas árabes e europeias.",
    description_es: "Atrevidos, refinados y duraderos. Nuestra selección de fragancias masculinas de las mejores casas árabes y europeas.",
    hero_image: "/images/categories/fragrances-men-hero.jpg"
  },
  {
    slug: "women",
    section: "fragrances",
    permalink: "fragrances/women.html",
    filter_type: "gender",
    filter_value: "Women",
    title_en: "Womens Fragrances",
    title_pt: "Perfumes Femininos",
    title_es: "Fragancias para Mujer",
    description_en: "Elegant, captivating and deeply personal. Our curated selection of women's fragrances from the finest Arabian and European houses.",
    description_pt: "Elegantes, cativantes e profundamente pessoais. A nossa seleção de perfumes femininos das melhores casas árabes e europeias.",
    description_es: "Elegantes, cautivadoras y profundamente personales. Nuestra selección de fragancias femeninas de las mejores casas árabes y europeas.",
    hero_image: "/images/categories/fragrances-women-hero.jpg"
  },
  {
    slug: "unisex",
    section: "fragrances",
    permalink: "fragrances/unisex.html",
    filter_type: "gender",
    filter_value: "Unisex",
    title_en: "Unisex Fragrances",
    title_pt: "Perfumes Unissexo",
    title_es: "Fragancias Unisex",
    description_en: "Beyond gender. Fragrances chosen for their character, not convention.",
    description_pt: "Além do género. Perfumes escolhidos pelo seu carácter, não pela convenção.",
    description_es: "Más allá del género. Fragancias elegidas por su carácter, no por la convención.",
    hero_image: "/images/categories/fragrances-unisex-hero.jpg"
  },
  {
    slug: "all-fragrances",
    section: "fragrances",
    permalink: "fragrances/all.html",
    filter_type: "type",
    filter_value: "fragrance",
    title_en: "All Fragrances",
    title_pt: "Todos os Perfumes",
    title_es: "Todas las Fragancias",
    description_en: "The complete YSP Collective fragrance edit — Arabian and European houses, every gender, every occasion.",
    description_pt: "A seleção completa de perfumes YSP Collective — casas árabes e europeias, todos os géneros, todas as ocasiões.",
    description_es: "La selección completa de fragancias YSP Collective — casas árabes y europeas, todos los géneros, todas las ocasiones.",
    hero_image: "/images/categories/fragrances-all-hero.jpg"
  },
  {
    slug: "all-beauty",
    section: "beauty",
    permalink: "beauty/all.html",
    filter_type: "type",
    filter_value: "beauty",
    title_en: "Beauty and Skincare",
    title_pt: "Beleza e Cuidado de Pele",
    title_es: "Belleza y Cuidado de la Piel",
    description_en: "Curated K-beauty and skincare — effective formulas, minimal ingredients, real results.",
    description_pt: "K-beauty e cuidado de pele curados — fórmulas eficazes, ingredientes mínimos, resultados reais.",
    description_es: "K-beauty y cuidado de la piel curados — fórmulas eficaces, ingredientes mínimos, resultados reales.",
    hero_image: "/images/categories/beauty-all-hero.jpg"
  },
  {
    slug: "spf-sunscreen",
    section: "beauty",
    permalink: "beauty/spf-sunscreen.html",
    filter_type: "category",
    filter_value: "SPF",
    title_en: "SPF Sunscreen",
    title_pt: "Protetor Solar",
    title_es: "Protección Solar",
    description_en: "Korean SPF that you'll actually want to wear — lightweight, no white cast, daily essential.",
    description_pt: "Protetor solar coreano que vai querer usar — leve, sem efeito branco, essencial diário.",
    description_es: "Protector solar coreano que querrás usar — ligero, sin tono blanco, esencial diario.",
    hero_image: "/images/categories/beauty-spf-hero.jpg"
  },
  {
    slug: "serums",
    section: "beauty",
    permalink: "beauty/serums.html",
    filter_type: "category",
    filter_value: "Serum",
    title_en: "Serums",
    title_pt: "Séruns",
    title_es: "Sérums",
    description_en: "Targeted treatments with proven actives. Find the right serum for your skin concern.",
    description_pt: "Tratamentos direcionados com ativos comprovados. Encontre o sérum certo para a sua preocupação.",
    description_es: "Tratamientos específicos con activos probados. Encuentra el sérum adecuado para tu preocupación.",
    hero_image: "/images/categories/beauty-serums-hero.jpg"
  },
  {
    slug: "moisturisers",
    section: "beauty",
    permalink: "beauty/moisturisers.html",
    filter_type: "category",
    filter_value: "Moisturiser",
    title_en: "Moisturisers",
    title_pt: "Hidratantes",
    title_es: "Hidratantes",
    description_en: "Hydration that works. Korean moisturisers for every skin type.",
    description_pt: "Hidratação que funciona. Hidratantes coreanos para todos os tipos de pele.",
    description_es: "Hidratación que funciona. Hidratantes coreanos para todo tipo de piel.",
    hero_image: "/images/categories/beauty-moisturisers-hero.jpg"
  },
  {
    slug: "cleansers",
    section: "beauty",
    permalink: "beauty/cleansers.html",
    filter_type: "category",
    filter_value: "Cleanser",
    title_en: "Cleansers",
    title_pt: "Limpadores",
    title_es: "Limpiadores",
    description_en: "The foundation of every good routine. Gentle, effective Korean cleansers.",
    description_pt: "A base de qualquer boa rotina. Limpadores coreanos suaves e eficazes.",
    description_es: "La base de cualquier buena rutina. Limpiadores coreanos suaves y eficaces.",
    hero_image: "/images/categories/beauty-cleansers-hero.jpg"
  }
];
